local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10
   publish_frequency: 10
   width: 1
   height: 10
   resolution: 0.05
   static_map: false
   rolling_window: true